"""drop user table

Revision ID: 280092e4b641
Revises: e358e791b829
Create Date: 2026-04-03 17:38:10.876637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280092e4b641'
down_revision: Union[str, Sequence[str], None] = 'e358e791b829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_access_token'), table_name='user')
    op.drop_index(op.f('ix_user_account'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('register_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('register_time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('usdt_assets', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('binance_api_arr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hot_key_config_obj', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_config_obj', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('server_info_obj', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('show_symbol_obj', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_account'), 'user', ['account'], unique=False)
    op.create_index(op.f('ix_user_access_token'), 'user', ['access_token'], unique=False)
    # ### end Alembic commands ###
