"""initial schema

Revision ID: 9783ae42b07c
Revises: 
Create Date: 2026-04-02 17:26:29.729357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9783ae42b07c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_access_token'), 'chat', ['access_token'], unique=False)
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_index', sa.Integer(), nullable=False),
    sa.Column('income_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('bnb_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trade_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_ts', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('my_ts', sa.BigInteger(), nullable=True),
    sa.Column('instrument_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('coin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_machine_index'), 'commission', ['machine_index'], unique=False)
    op.create_index(op.f('ix_commission_symbol'), 'commission', ['symbol'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('income_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('bnb_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trade_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_ts', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_access_token'), 'income', ['access_token'], unique=False)
    op.create_index(op.f('ix_income_symbol'), 'income', ['symbol'], unique=False)
    op.create_table('income_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('day_begin_time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('day_end_time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('zjy_commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_day_api_key'), 'income_day', ['api_key'], unique=False)
    op.create_table('loss_limit_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('limit_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loss_limit_time_symbol'), 'loss_limit_time', ['symbol'], unique=True)
    op.create_table('machine_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('insert_ts', sa.BigInteger(), nullable=True),
    sa.Column('update_ts', sa.BigInteger(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('run_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_status_private_ip'), 'machine_status', ['private_ip'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('client_order_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cum_quote', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('executed_qty', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('orig_qty', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('orig_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('reduce_only', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('position_side', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('close_position', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('time_in_force', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('order_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('update_time', sa.BigInteger(), nullable=True),
    sa.Column('working_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('price_protect', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('binance_ts', sa.BigInteger(), nullable=True),
    sa.Column('my_ts', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_symbol'), 'order', ['symbol'], unique=False)
    op.create_table('position_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('unrealized_profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('position_amt', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('position_value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('update_profit_and_commission', sa.Boolean(), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('maker_commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_record_symbol'), 'position_record', ['symbol'], unique=False)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('buyer', sa.Boolean(), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('binance_id', sa.BigInteger(), nullable=True),
    sa.Column('maker', sa.Boolean(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('qty', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quote_qty', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('position_side', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('my_ts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_symbol'), 'trade', ['symbol'], unique=False)
    op.create_table('trade_machine_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('insert_ts', sa.BigInteger(), nullable=True),
    sa.Column('update_ts', sa.BigInteger(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('run_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_machine_status_private_ip'), 'trade_machine_status', ['private_ip'], unique=False)
    op.create_table('trade_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('begin_ts', sa.BigInteger(), nullable=True),
    sa.Column('end_ts', sa.BigInteger(), nullable=True),
    sa.Column('profit_percent_by_balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('vol_info', sa.JSON(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_record_symbol'), 'trade_record', ['symbol'], unique=False)
    op.create_table('trade_server_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('extra_para', sa.Text(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('my_symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('run_info', sa.Text(), nullable=True),
    sa.Column('update_ts', sa.BigInteger(), nullable=True),
    sa.Column('update_time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_server_status_private_ip'), 'trade_server_status', ['private_ip'], unique=False)
    op.create_table('trade_symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('coin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('onboard_date', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('default_show', sa.Boolean(), nullable=True),
    sa.Column('onboard_ts', sa.Integer(), nullable=True),
    sa.Column('link_symbol_arr', sa.JSON(), nullable=True),
    sa.Column('quote_volume', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('quote_volume_rank', sa.Integer(), nullable=True),
    sa.Column('link_private_ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('machine_run_ts', sa.BigInteger(), nullable=True),
    sa.Column('machine_run_time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_symbol_symbol'), 'trade_symbol', ['symbol'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('register_ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('register_time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('usdt_assets', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_api_arr', sa.Text(), nullable=True),
    sa.Column('hot_key_config_obj', sa.Text(), nullable=True),
    sa.Column('state_config_obj', sa.Text(), nullable=True),
    sa.Column('server_info_obj', sa.Text(), nullable=True),
    sa.Column('show_symbol_obj', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_token'), 'user', ['access_token'], unique=False)
    op.create_index(op.f('ix_user_account'), 'user', ['account'], unique=False)
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('page', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    op.drop_index(op.f('ix_user_account'), table_name='user')
    op.drop_index(op.f('ix_user_access_token'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trade_symbol_symbol'), table_name='trade_symbol')
    op.drop_table('trade_symbol')
    op.drop_index(op.f('ix_trade_server_status_private_ip'), table_name='trade_server_status')
    op.drop_table('trade_server_status')
    op.drop_index(op.f('ix_trade_record_symbol'), table_name='trade_record')
    op.drop_table('trade_record')
    op.drop_index(op.f('ix_trade_machine_status_private_ip'), table_name='trade_machine_status')
    op.drop_table('trade_machine_status')
    op.drop_index(op.f('ix_trade_symbol'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_position_record_symbol'), table_name='position_record')
    op.drop_table('position_record')
    op.drop_index(op.f('ix_order_symbol'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_machine_status_private_ip'), table_name='machine_status')
    op.drop_table('machine_status')
    op.drop_index(op.f('ix_loss_limit_time_symbol'), table_name='loss_limit_time')
    op.drop_table('loss_limit_time')
    op.drop_index(op.f('ix_income_day_api_key'), table_name='income_day')
    op.drop_table('income_day')
    op.drop_index(op.f('ix_income_symbol'), table_name='income')
    op.drop_index(op.f('ix_income_access_token'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_commission_symbol'), table_name='commission')
    op.drop_index(op.f('ix_commission_machine_index'), table_name='commission')
    op.drop_table('commission')
    op.drop_index(op.f('ix_chat_access_token'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
