"""convert time string fields to timestamptz

Revision ID: d06ff177ba08
Revises: 280092e4b641
Create Date: 2026-04-03 19:00:41.626345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06ff177ba08'
down_revision: Union[str, Sequence[str], None] = '280092e4b641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income_day', 'day_begin_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='day_begin_time::timestamp with time zone')
    op.alter_column('income_day', 'day_end_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='day_end_time::timestamp with time zone')
    op.alter_column('position_record', 'time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='time::timestamp with time zone')
    op.alter_column('trade_server_status', 'update_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='update_time::timestamp with time zone')
    op.alter_column('trade_symbol', 'machine_run_time',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='machine_run_time::timestamp with time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_symbol', 'machine_run_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('trade_server_status', 'update_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('position_record', 'time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('income_day', 'day_end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('income_day', 'day_begin_time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
