"""drop chat and visitor tables

Revision ID: e358e791b829
Revises: 9783ae42b07c
Create Date: 2026-04-03 00:13:20.301623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e358e791b829'
down_revision: Union[str, Sequence[str], None] = '9783ae42b07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    op.drop_index(op.f('ix_chat_access_token'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chat_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_pkey'))
    )
    op.create_index(op.f('ix_chat_access_token'), 'chat', ['access_token'], unique=False)
    op.create_table('visitor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('page', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_pkey'))
    )
    # ### end Alembic commands ###
