"""add new tables and model field updates

Revision ID: ff88280b01a3
Revises: d06ff177ba08
Create Date: 2026-04-03 21:55:08.614514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff88280b01a3'
down_revision: Union[str, Sequence[str], None] = 'd06ff177ba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('begin_trade_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('asks_depth_arr', sa.Text(), nullable=True),
    sa.Column('bids_depth_arr', sa.Text(), nullable=True),
    sa.Column('orders_result', sa.Text(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('machine_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.Column('my_trade_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('now_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_begin_trade_record_symbol'), 'begin_trade_record', ['symbol'], unique=False)
    op.create_table('commission_temp_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('bnb_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trade_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_ts', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('my_ts', sa.BigInteger(), nullable=True),
    sa.Column('instrument_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('coin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_history_take',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('bnb_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('trade_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('binance_ts', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('my_ts', sa.BigInteger(), nullable=True),
    sa.Column('instrument_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('coin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_history_take_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_begin_time', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('day_end_time', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('vol_multiple', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('standard_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('kline_arr', sa.Text(), nullable=True),
    sa.Column('now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('begin_machine_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('longs_condition_a', sa.Integer(), nullable=True),
    sa.Column('shorts_condition_a', sa.Integer(), nullable=True),
    sa.Column('shorts_condition_b', sa.Integer(), nullable=True),
    sa.Column('btc_now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('eth_now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('begin_ts', sa.BigInteger(), nullable=True),
    sa.Column('end_ts', sa.BigInteger(), nullable=True),
    sa.Column('trade_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('update_ts', sa.BigInteger(), nullable=True),
    sa.Column('client_begin_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('client_end_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('vol_info', sa.Text(), nullable=True),
    sa.Column('open_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('open_time', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.Integer(), nullable=True),
    sa.Column('close_time', sa.Integer(), nullable=True),
    sa.Column('open_gtx_time', sa.Integer(), nullable=True),
    sa.Column('add_gtx_time', sa.Integer(), nullable=True),
    sa.Column('close_gtx_time', sa.Integer(), nullable=True),
    sa.Column('take_time', sa.Integer(), nullable=True),
    sa.Column('begin_boll_up', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('begin_boll_down', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('take_value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('trades_take',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_ts', sa.BigInteger(), nullable=True),
    sa.Column('end_ts', sa.BigInteger(), nullable=True),
    sa.Column('profit_percent_by_balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('income', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('commission', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('vol_info', sa.JSON(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('vol_multiple', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('standard_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('kline_arr', sa.Text(), nullable=True),
    sa.Column('now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('begin_machine_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('longs_condition_a', sa.Integer(), nullable=True),
    sa.Column('shorts_condition_a', sa.Integer(), nullable=True),
    sa.Column('shorts_condition_b', sa.Integer(), nullable=True),
    sa.Column('btc_now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('eth_now_open_rate', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('trade_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('update_ts', sa.BigInteger(), nullable=True),
    sa.Column('client_begin_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('client_end_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('loss_limit_time', 'limit_time',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loss_limit_time', 'limit_time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('trades_take')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('income_history_take_day')
    op.drop_table('income_history_take')
    op.drop_table('commission_temp_income')
    op.drop_index(op.f('ix_begin_trade_record_symbol'), table_name='begin_trade_record')
    op.drop_table('begin_trade_record')
    # ### end Alembic commands ###
